### ISSUE TITLE
Fatal Errorr

### ISSUE THREAD

**Issue by Minglong2012** [openaicellular/oaic#65] opened 2022-12-28 00:29 UTC
fatal: No url found for submodule path 'asn1c' in .gitmodules

**Comment by jgaeddert** [comment] 2022-12-28 19:00
That's correct: we don't pull asn1c as a submodule. The instructions call for cloning it separately; however we should probably find an alternative way to install it

**Comment by joshuamoorexyz** [comment] 2022-12-29 21:31
Fixed by adding the following to .gitmodules in oaic repo

[submodule "asn1c"]
                 path = asn1c
                 url = https://gitlab.eurocom.fr/oai/asn1c.git


This repo is in the instructions, but one cannot access all other linked repos because asn1c is still linked. If we are going to clone the repo later, it should be unlinked as a submodule

How to reproduce: clone the oaic repo fresh and try the command "git submodule update --init"

**Closed** 2023-01-06 19:58 UTC

**Comment by pratheeksu** [comment] 2023-01-06 20:47
I pushed a fix linking the asn1 repo we need.
